login:
   type: rest
   resource: App\Controller\RestLoginController

profile:
   type: rest
   resource: App\Controller\UserController

project:
   type: rest
   resource: App\Controller\ProjectsController

projectCreate:
   type: rest
   resource: App\Controller\ProjectCreateController

home:
   type: rest
   resource: App\Controller\HomeController
