security:
   encoders:
       FOS\UserBundle\Model\UserInterface: bcrypt

   role_hierarchy:
       ROLE_ADMIN:       ROLE_USER
       ROLE_SUPER_ADMIN: ROLE_ADMIN

   providers:
       fos_userbundle:
           id: fos_user.user_provider.username_email

   firewalls:
       dev:
           pattern: ^Api/(_(profiler|wdt)|css|images|js)/
           security: false

       api_login:
           pattern:  ^Api/login
           stateless: true
           anonymous: true
           form_login:
               check_path:               Api/login
               require_previous_session: false
               username_parameter:       username
               password_parameter:       password
               success_handler:          lexik_jwt_authentication.handler.authentication_success
               failure_handler:          lexik_jwt_authentication.handler.authentication_failure

       api:
           pattern:   ^Api/
           stateless: true
           lexik_jwt: ~


   access_control:
       - { path: ^Api/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^Api/, role: IS_AUTHENTICATED_FULLY }
