login:
   type: rest
   resource: App\Controller\Api\RestLoginController

profile:
   type: rest
   resource: App\Controller\Api\UserController

project:
   type: rest
   resource: App\Controller\Api\ProjectsController

projectCreate:
   type: rest
   resource: App\Controller\Api\ProjectCreateController
